services:
  elearninguploader:
    image: node:24-slim
    container_name: elearninguploader
    hostname: elearninguploader
    user: "1000:1000"

    working_dir: /app

    ports:
      - "8004:5173"

    volumes:
      - .:/app

    command: npm run dev -- --host 0.0.0.0

    restart: unless-stopped
